### ISSUE TITLE
关于api的使用

### ISSUE THREAD

**Issue by XingYing-stack** [EachSheep/ShortcutsBench#2]
您好，感谢您杰出的工作！

请问您是如何收集API的参数调用信息的， 即API metadata (function description, name, parameter names, parameter types, parameter default values, return value names, etc.)

可以更新一下这部分的数据集吗？

**Comment by EachSheep** [comment]
感谢您的关注！我们正在积极整理相关API信息以及评测代码和结果，会在近期尽快发布！

**Comment by EachSheep** [comment]
> 您好，感谢您杰出的工作！
> 
> 请问您是如何收集API的参数调用信息的， 即API metadata (function description, name, parameter names, parameter types, parameter default values, return value names, etc.)
> 
> 可以更新一下这部分的数据集吗？

有关API的收集方法，您可以关注我们的论文：https://arxiv.org/pdf/2407.00132
具体的收集的API，我们会在近期尽快发布！

**Comment by XingYing-stack** [comment]
感谢您的回复！ 
请问相应的apppendix在哪里可以找到呢？
此外，我比较好奇API的入参和出参等API metadata似乎并不能直观地从.shortcut文件中统计，这是怎么得到的呢？
